/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PainelMestreRouteImport } from './routes/painel-mestre'
import { Route as AcompanharRouteImport } from './routes/acompanhar'
import { Route as AbrirRouteImport } from './routes/abrir'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogKpisHelpdeskHospitalarRouteImport } from './routes/blog.kpis-helpdesk-hospitalar'
import { Route as AuthSetorRouteImport } from './routes/auth.$setor'
import { Route as AppSetorRouteImport } from './routes/app.$setor'

const PainelMestreRoute = PainelMestreRouteImport.update({
  id: '/painel-mestre',
  path: '/painel-mestre',
  getParentRoute: () => rootRouteImport,
} as any)
const AcompanharRoute = AcompanharRouteImport.update({
  id: '/acompanhar',
  path: '/acompanhar',
  getParentRoute: () => rootRouteImport,
} as any)
const AbrirRoute = AbrirRouteImport.update({
  id: '/abrir',
  path: '/abrir',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogKpisHelpdeskHospitalarRoute =
  BlogKpisHelpdeskHospitalarRouteImport.update({
    id: '/blog/kpis-helpdesk-hospitalar',
    path: '/blog/kpis-helpdesk-hospitalar',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthSetorRoute = AuthSetorRouteImport.update({
  id: '/auth/$setor',
  path: '/auth/$setor',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSetorRoute = AppSetorRouteImport.update({
  id: '/app/$setor',
  path: '/app/$setor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abrir': typeof AbrirRoute
  '/acompanhar': typeof AcompanharRoute
  '/painel-mestre': typeof PainelMestreRoute
  '/app/$setor': typeof AppSetorRoute
  '/auth/$setor': typeof AuthSetorRoute
  '/blog/kpis-helpdesk-hospitalar': typeof BlogKpisHelpdeskHospitalarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abrir': typeof AbrirRoute
  '/acompanhar': typeof AcompanharRoute
  '/painel-mestre': typeof PainelMestreRoute
  '/app/$setor': typeof AppSetorRoute
  '/auth/$setor': typeof AuthSetorRoute
  '/blog/kpis-helpdesk-hospitalar': typeof BlogKpisHelpdeskHospitalarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abrir': typeof AbrirRoute
  '/acompanhar': typeof AcompanharRoute
  '/painel-mestre': typeof PainelMestreRoute
  '/app/$setor': typeof AppSetorRoute
  '/auth/$setor': typeof AuthSetorRoute
  '/blog/kpis-helpdesk-hospitalar': typeof BlogKpisHelpdeskHospitalarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abrir'
    | '/acompanhar'
    | '/painel-mestre'
    | '/app/$setor'
    | '/auth/$setor'
    | '/blog/kpis-helpdesk-hospitalar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abrir'
    | '/acompanhar'
    | '/painel-mestre'
    | '/app/$setor'
    | '/auth/$setor'
    | '/blog/kpis-helpdesk-hospitalar'
  id:
    | '__root__'
    | '/'
    | '/abrir'
    | '/acompanhar'
    | '/painel-mestre'
    | '/app/$setor'
    | '/auth/$setor'
    | '/blog/kpis-helpdesk-hospitalar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbrirRoute: typeof AbrirRoute
  AcompanharRoute: typeof AcompanharRoute
  PainelMestreRoute: typeof PainelMestreRoute
  AppSetorRoute: typeof AppSetorRoute
  AuthSetorRoute: typeof AuthSetorRoute
  BlogKpisHelpdeskHospitalarRoute: typeof BlogKpisHelpdeskHospitalarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/painel-mestre': {
      id: '/painel-mestre'
      path: '/painel-mestre'
      fullPath: '/painel-mestre'
      preLoaderRoute: typeof PainelMestreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acompanhar': {
      id: '/acompanhar'
      path: '/acompanhar'
      fullPath: '/acompanhar'
      preLoaderRoute: typeof AcompanharRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abrir': {
      id: '/abrir'
      path: '/abrir'
      fullPath: '/abrir'
      preLoaderRoute: typeof AbrirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/kpis-helpdesk-hospitalar': {
      id: '/blog/kpis-helpdesk-hospitalar'
      path: '/blog/kpis-helpdesk-hospitalar'
      fullPath: '/blog/kpis-helpdesk-hospitalar'
      preLoaderRoute: typeof BlogKpisHelpdeskHospitalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$setor': {
      id: '/auth/$setor'
      path: '/auth/$setor'
      fullPath: '/auth/$setor'
      preLoaderRoute: typeof AuthSetorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$setor': {
      id: '/app/$setor'
      path: '/app/$setor'
      fullPath: '/app/$setor'
      preLoaderRoute: typeof AppSetorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbrirRoute: AbrirRoute,
  AcompanharRoute: AcompanharRoute,
  PainelMestreRoute: PainelMestreRoute,
  AppSetorRoute: AppSetorRoute,
  AuthSetorRoute: AuthSetorRoute,
  BlogKpisHelpdeskHospitalarRoute: BlogKpisHelpdeskHospitalarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
