/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSetorRouteImport } from './routes/auth.$setor'
import { Route as AppSetorRouteImport } from './routes/app.$setor'
import { Route as AbrirSetorRouteImport } from './routes/abrir.$setor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSetorRoute = AuthSetorRouteImport.update({
  id: '/auth/$setor',
  path: '/auth/$setor',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSetorRoute = AppSetorRouteImport.update({
  id: '/app/$setor',
  path: '/app/$setor',
  getParentRoute: () => rootRouteImport,
} as any)
const AbrirSetorRoute = AbrirSetorRouteImport.update({
  id: '/abrir/$setor',
  path: '/abrir/$setor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abrir/$setor': typeof AbrirSetorRoute
  '/app/$setor': typeof AppSetorRoute
  '/auth/$setor': typeof AuthSetorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abrir/$setor': typeof AbrirSetorRoute
  '/app/$setor': typeof AppSetorRoute
  '/auth/$setor': typeof AuthSetorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abrir/$setor': typeof AbrirSetorRoute
  '/app/$setor': typeof AppSetorRoute
  '/auth/$setor': typeof AuthSetorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/abrir/$setor' | '/app/$setor' | '/auth/$setor'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/abrir/$setor' | '/app/$setor' | '/auth/$setor'
  id: '__root__' | '/' | '/abrir/$setor' | '/app/$setor' | '/auth/$setor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbrirSetorRoute: typeof AbrirSetorRoute
  AppSetorRoute: typeof AppSetorRoute
  AuthSetorRoute: typeof AuthSetorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$setor': {
      id: '/auth/$setor'
      path: '/auth/$setor'
      fullPath: '/auth/$setor'
      preLoaderRoute: typeof AuthSetorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/$setor': {
      id: '/app/$setor'
      path: '/app/$setor'
      fullPath: '/app/$setor'
      preLoaderRoute: typeof AppSetorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abrir/$setor': {
      id: '/abrir/$setor'
      path: '/abrir/$setor'
      fullPath: '/abrir/$setor'
      preLoaderRoute: typeof AbrirSetorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbrirSetorRoute: AbrirSetorRoute,
  AppSetorRoute: AppSetorRoute,
  AuthSetorRoute: AuthSetorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
